### ISSUE TITLE
Module Error

### ISSUE THREAD

**Issue by zakirkun** [slowy07/luna#12]
im trying import Text2Image but module not found

**Comment by slowy07** [comment]
hello @zakirkun, ``Text2Image`` module error cause breaking change from latest luna which change to ``StableDiffusion``.

soon we will fix this, specially demo on online demo, but, you can try by using ``v1.0.0`` version [here](https://github.com/slowy07/luna/releases/tag/1.0.0) on local, if you want try to test on online demo, soon, we will fix it, thanks !

**Comment by slowy07** [comment]
hello @zakirkun , online demo for old version has fixing, and running very well, you can check [here](https://colab.research.google.com/drive/1IyHaYLCPLRurVs-tJJRLbCcO4kr1xlOi?usp=sharing) and for install on local you can check here, including documentation for installing and running offline colab runtime ([Luna v1.0.0](https://github.com/slowy07/luna/releases/tag/1.0.0))

thanks !
